server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: tomcat
  static_configs:
  - targets:
      - localhost
    labels:
      job: tomcat
      __path__: /tomcatlog/localhost_access_log*
  pipeline_stages:
  - regex:      
      expression: '^(?P<ip>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}).*\[(?P<time>\d{2}\/\w{3}\/\d{4}:\d{2}:\d{2}:\d{2} \+\d{4})\] "(?P<method>\w+) (?P<url>.*) (.*)" (?P<status>\d+)'
  - timestamp:
      source: time
      format: '02/Jan/2006:15:04:05 -0700'
  - regex:
      expression: '^(?P<urlwithoutparm>.*?)(\?.*)?$'
      source: url
  - labels:
      ip:
      time:
      method:
      url:
      status:
      urlwithoutparm:
  - output:
      source: message

    